mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from home import views 



urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),

    
]

polls/urls.py
from django.urls import path

from . import views
from django.conf.urls import url

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),

    path('comments/list/', views.commentLists, name='commentLists'),
    path('comments/', views.makeComment, name='makeComment'),
    path('post-comment/', views.postComment, name='postComment'),
    

]

home/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    notMuchVotes = models.IntegerField(null=True)
    theSkyeVotes = models.IntegerField(null=True)
    from django.db import models

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
        
class Post(models.Model):
    author = models.ForeignKey(Question, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text




    

polls/forms.py
from .models import Post, Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'text',)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def home_view(request):
    return render(request, "home.html")

                  

polls/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render


from .models import Question, Choice
from .models import Post, Comment





def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    dataIn = request.POST.copy()
    try:
        question = Question.objects.get(id=question_id)
        if int(dataIn['choice']) == 10:
            currentVotes = question.notMuchVotes
            question.notMuchVotes = currentVotes + 1
        else:
            currentVotes = question.theSkyeVotes
            question.theSkyeVotes = currentVotes + 1
        question.save()
    except:
        pass


    question = get_object_or_404(Question, pk=question_id)
    
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

def makeComment(request):
    someData = {}
    someData['anyData'] = 'anyValue'
    someData['posts'] = Question.objects.order_by('-pub_date')[:5]
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'

    return render(request, 'polls/make-comment.html', someData)



def postComment(request):
    dataIn = request.POST.copy()
    post = dataIn['post']
    name = dataIn['name']
    comments = dataIn['comments']


    commentModel = Comment()
    commentModel.post = Question.objects.get(id=post)
    commentModel.author = name
    commentModel.text = comments
    commentModel.save()

    return redirect('/polls/comments/list/')


def commentLists(request):
    someData = {}
    someData['anyData'] = 'anyValue'
    someData['comments'] = Comment.objects.order_by('-created_date')
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'
    # someData['anyData'] = 'anyValue'

    # print(someData)

    return render(request, 'polls/comment-lists.html', someData)

  

home/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock title%}
    </title>
    {% block custom_css %}{% endblock custom_css%}
    <body>

        {% block body_data %}{% endblock body_data%}

   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


    {% block custom_js %}{% endblock custom_js%}
</body>
<style>


.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
</style>
</head>
<body>

home/templates/home.html
{% extends 'base_template.html' %}


{% block title %}
Homepage
{% endblock title %}

{% block body_data %}

<!DOCTYPE html>
<html lang="en">

    <head>
<div>
    <h2>This is Hasan's first Django Site</h2>
</div>

 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<style>
.footer_container{
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(161, 174, 190, 0.938)
  }

.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
</style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="polls/comments/" googl="true">Comments</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="polls/comments/list"> Comment List <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    

<div class="footer_container">
  <!-- Footer -->
  <footer class="page-footer font-small blue">
  
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
        <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
      </div>
      <!-- Copyright -->
    
    </footer>
    <!-- Footer -->

    
  </div>

</html>
</body>


{% endblock body_data %}


    

polls/templates/polls/comment-lists.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<style>
.footer_container{

position: absolute;

left: 0;

right: 0;

bottom: 0;
background-color: rgba(161, 174, 190, 0.938)
}
.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
</style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      
    <div class="our_page_container">

        <table class="table table-condensed">
            <thead>
            <tr>
              <th>Name</th>
              <th>Comments</th>
              <th>Created Date</th>
            </tr>
            </thead>
            <tbody>
            {% for getN in comments %}
            <tr>
              <td googl="true">{{getN.author}}</td>
              <td>{{getN.text}}</td>
              <td>{{getN.created_date}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</body>

<div class="footer_container">
  <!-- Footer -->
  <footer class="page-footer font-small blue">
  
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
        <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
      </div>
      <!-- Copyright -->
    
    </footer>
    <!-- Footer -->
  </div>

</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">





<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<style>
.footer_container{

position: absolute;

left: 0;

right: 0;

bottom: 0;
background-color: rgba(161, 174, 190, 0.938)
}
.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
</style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/polls/comments/">Comments <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/polls/comments/list">Comments List <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      
      <h1>{{ question.question_text }}</h1>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="mx-auto" style="width: 200px;" padding-top= ".25px;"">
    <form action="{% url 'polls:results' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
  </div>

 
</body>


</html>




<div class="footer_container">
  <!-- Footer -->
  <footer class="page-footer font-small blue">
  
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
        <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
      </div>
      <!-- Copyright -->
    
    </footer>
    <!-- Footer -->
  </div>

</form>

polls/templates/polls/index.html
{% if latest_question_list %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<style>
.footer_container{

position: absolute;

left: 0;

right: 0;

bottom: 0;
background-color: rgba(161, 174, 190, 0.938)
}
.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
</style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      
   





        
</body>
<style>
    .page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
    .page_container{text-align: center;} 
    </style>

<div class="page_container">
<div>
    {% for question in latest_question_list %}
    <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    
</div> 
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% load static %}

</div>

<div class="footer_container">
    <!-- Footer -->
    <footer class="page-footer font-small blue">
    
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
          <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
        </div>
        <!-- Copyright -->
      
      </footer>
      <!-- Footer -->
    </div>


<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

polls/templates/polls/make-comment.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Comments Page</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <style>
    .footer_container{

position: absolute;

left: 0;

right: 0;

bottom: 0;
background-color: rgba(161, 174, 190, 0.938)

}
    .our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}
    </style>
    </head>
    <body>
    
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
      
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
    
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </nav>
    
    <div class="our_page_container">

        <form method="POST" action="/polls/post-comment/">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Post</label>
                <select name="post" id="">
                    <option value="">Select Post</option>
                    {% for getN in posts %}
                    <option value="{{getN.id}}">{{getN.question_text}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input name="name" type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter name">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Comments</label>
              <textarea name="comments"  class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</body>
<div class="footer_container">
<!-- Footer -->
<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
      <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
</div>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<style>
.our_page_container{ width: 100%; max-width: 600px; margin: 100px auto;}


</style>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/polls/" googl="true">Polls</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      
   





        
</body>
<style>
    .container{ width: 100%; max-width: 600px; margin: 100px auto;}
    .container{text-align: center;} 
    
    .footer_container{
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(161, 174, 190, 0.938)
  }
    </style>

<div class="container">
  <div>
    <li>Option 1 Votes : {{question.notMuchVotes}}</li>
    <li>Option 2 Votes : {{question.theSkyeVotes}}</li>
  </div>

  <div class="footer_container">
    <!-- Footer -->
    <footer class="page-footer font-small blue">
    
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2020 Copyright, Hasan Mukati:
          <a href="https://Hasanmukati.com/"> Hasanmukati.com</a>
        </div>
        <!-- Copyright -->
      
      </footer>
      <!-- Footer -->
    </div>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>